name: issue-to-project
on:
  issues:
    types:
      - opened

jobs:
  manage_project:
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/hr951-MC/projects/1
          github-token: ${{ secrets.TOKEN }}
