name: issue-to-project
on:
  issues:
    types:
      - opened

jobs:
  manage_project:
    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate github token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.TOKEN }}
          
      - name: Add Issue to Project
        uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/hr951-MC/projects/1
          github-token: ${{ steps.generate_token.outputs.token }}
