name: issue-to-project
on:
  issues:
    types:
      - opened

jobs:
  manage_project:
    runs-on: ubuntu-22.04
    steps:
      - name: get_token
        run 
      - name: Add Issue to Project
        uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/hr951-MC/projects/1
          github-token: ${{ steps.generate_token.outputs.token }}
